# set default editor
export EDITOR='/usr/bin/vim'
export VISUAL='/usr/bin/vim'


# direnv 
# Add direnv hook
if hash direnv 2>/dev/null; then
    eval "$(direnv hook zsh)"
fi
export DIRENV_LOG_FORMAT=   # remove direnv log loading
