(source "gnu"   "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
(source "melpa" "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")

;; appearance
(depends-on "doom-themes")
(depends-on "dashboard")
(depends-on "hlinum")
(depends-on "moe-theme")

;; evil-mode
(depends-on "evil")
(depends-on "evil-visualstar")
(depends-on "evil-leader")
(depends-on "evil-surround")
(depends-on "evil-nerd-commenter")
(depends-on "evil-quickscope")

;; company-snippets
(depends-on "company")
(depends-on "yasnippet")
(depends-on "yasnippet-snippets")

;; helm
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-swoop")
(depends-on "helm-describe-modes")

;;lsp
(depends-on "lsp-mode")
(depends-on "lsp-python")
;;(depends-on "ccls")
(depends-on "lsp-clangd")
(depends-on "lsp-ui")
(depends-on "company-lsp")


;;python
(depends-on "anaconda-mode")
(depends-on "company-anaconda")


;;flycheck
(depends-on "flycheck")
(depends-on "helm-flycheck")


;;progamming
(depends-on "rmsbolt")
(depends-on "quickrun")
(depends-on "indent-guide")


;;c/cpp
(depends-on "clang-format")
(depends-on "irony")
(depends-on "company-irony")
(depends-on "company-irony-c-headers")

;; org-mode
(depends-on "org")
(depends-on "org-cliplink")
(depends-on "org-download")

;; tools
(depends-on "youdao-dictionary")
(depends-on "google-this")
(depends-on "avy")
(depends-on "fcitx")
(depends-on "helpful")
(depends-on "multiple-cursors")

;; better-default
(depends-on "which-key")
(depends-on "iedit")
(depends-on "super-save")
(depends-on "autopair")
(depends-on "highlight-indentation")
(depends-on "restart-emacs")
(depends-on "undo-tree")
(depends-on "rainbow-delimiters")
(depends-on "hungry-delete")
(depends-on "nyan-mode")
(depends-on "exec-path-from-shell")


;;git
(depends-on "magit")

(depends-on "async")
(depends-on "dash")
(depends-on "projectile")
