patch:
  "translator/dictionary": luna_pinyin_simp.extended
  "speller/algebra":
      - derive/^([zcs])h/$1/ #zh,ch,sh->z,c,s
      - derive/^([zcs])([^h])/$1h$2/ #z,c,s->zh,ch,sh
      - derive/^n/l #n->l
      - derive/^l/n #l->n
      - derive/([ei])n$/$1ng/  # en -> eng, in -> ing
      - derive/([ei])ng$/$1n/ # eng->en, ing -> in
      - abbrev/^([a-z]).+$/$1/ #简拼支持
      - abbrev/^([zcs]h).+$/$1/ #模糊音的简拼支持
      delimiter: " '" #分隔符
