name: luna_pinyin_simp.extended
version: "2020.07.08"
sort: by_weight
use_preset_vocabulary: false #是否启用默认的“八股文”词库及词频系统,如需启用请设为 true 。
import_tables:
  - zhwiki
  - moegirl
  - luna_pinyin.computer.dict
...
