name: py352
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - ca-certificates=2018.10.15
  - cerberus=1.2
  - certifi=2018.8.24
  - greenlet=0.4.13
  - jedi=0.12.1
  - libgcc-ng=7.2.0
  - libstdcxx-ng=7.2.0
  - msgpack-python=0.5.6
  - ncurses=5.9
  - neovim=0.2.6
  - openssl=1.0.2p
  - parso=0.3.1
  - pip=18.0
  - python=3.5.2
  - readline=6.2
  - setuptools=40.4.3
  - sqlite=3.13.0
  - tk=8.5.19
  - wheel=0.32.0
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - msgpack==0.5.6
