source $HOME/.antigen/antigen.zsh

# oh-my-zsh
antigen use oh-my-zsh

if [ -d /etc/apt ];then
  antigen bundle debian
elif [ -d /etc/pacman.d ];then
  antigen bundle archlinux
fi
if [[ "$OSTYPE" == "darwin"* ]]; then
  antigen bundle osx
  antigen bundle brew
fi
antigen bundles <<EOB
# systemd
git
autojump
extract
tmux
sudo
copydir
command-not-found
copyfile
# py
python
pip
# js
npm
# rb
ruby
rbenv
gem
# clojure
lein
EOB
# --------------------------------------------other -------------------------------------------- #
antigen bundles <<EOB
# unixorn/autoupdate-antigen.zshplugin
RobSis/zsh-completion-generator
zsh-users/zsh-autosuggestions
zsh-users/zsh-completions
zsh-users/zsh-syntax-highlighting
changyuheng/zsh-interactive-cd
hlissner/zsh-autopair
Tarrasch/zsh-bd
djui/alias-tips
gujiaxi/ranger-cd
# js
# py
gangleri/pipenv
EOB

# RobSis/zsh-completion-generator
GENCOMPL_FPATH=$HOME/.zsh/complete
zstyle :plugin:zsh-completion-generator clang 

# Load the theme.
antigen theme robwierzbowski/charged-zsh-theme

# # Tell Antigen that you're done.
antigen apply

# alias
. $HOME/.zshaliases
# function
. $HOME/.zshfunction

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh



